DROP USER CA103;
CREATE USER CA103 IDENTIFIED BY 123456;
GRANT CONNECT, RESOURCE, DBA, EXP_FULL_DATABASE, IMP_FULL_DATABASE TO CA103;
GRANT UNLIMITED TABLESPACE TO CA103;
SELECT USERNAME FROM ALL_USERS ORDER BY USERNAME;
exit
