DROP USER T3MS;
CREATE USER T3MS IDENTIFIED BY 123456;
GRANT CONNECT, RESOURCE, DBA, EXP_FULL_DATABASE, IMP_FULL_DATABASE TO T3MS;
GRANT UNLIMITED TABLESPACE TO T3MS;
SELECT USERNAME FROM ALL_USERS ORDER BY USERNAME;
exit
